@'
[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.121.2"    # replace with your local 'hugo version' if you have one
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GIT_SUBMODULE_STRATEGY = "recursive"
'@ | Set-Content -Encoding UTF8 netlify.toml
